// *Project Euler - Problem 12*

/* The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors? */

#include <stdio.h>
#include <limits.h>

//Protótipos
int achaDivs(int num);

int main(void)
{
//Declarações
	unsigned int qtdDiv = 0, num = 1, triNum = 0;
	
//Instruções
	do {
		qtdDiv = achaDivs(triNum);
		triNum += num;
		num++;
	}while(qtdDiv <= 500 && triNum <= INT_MAX);
	printf ("triNum: %d\nfactors: %d",triNum,qtdDiv);
	
	getchar();
	return 0;
}

//Subprogramas
	// Objetivo : Calcular a quantidade de divisores de um numero qualquer
	// Parâmaetros: Número inteiro
	// Retorno : Quantidade de divisores
	int achaDivs(int num)
	{
		int qtdDivs = 0, i;
		
		for (i = 1; i < num/2; i++) {
			if (num % i == 0)
				qtdDivs++;
		}
		qtdDivs++;
		if (qtdDivs > 400)
		   printf ("num %d factors %d\n",num,qtdDivs);
		
		return qtdDivs;
	}
